
import 'dotenv/config';
import OpenAI from "openai";


// Create a new OpenAI client.
//
// The `client` object will be used to send requests to OpenAI,
// such as generating chat responses.
const client = new OpenAI({

    // Read the API key from the environment variables.
    //
    // `process.env` contains environment variables available to Node.js.
    //
    // `OPENAI_API_KEY` should be defined inside your `.env` file:
    //
    // OPENAI_API_KEY=your_actual_api_key
    //
    // The API key authenticates your request and tells OpenAI
    // which account is making the API call.
    apiKey: process.env.OPENAI_API_KEY
});


// Send a request to the Chat Completions API.
//
// `client.chat.completions.create()` asks an OpenAI model
// to generate a response based on the messages provided.
client.chat.completions.create({

    // Specify which OpenAI model should process the request.
    //
    // Here, the request is sent to the `gpt-4.1-mini` model.
    //
    // The model parameter is required. Without it, the API
    // does not know which model should generate the response.
    model: "gpt-4.1-mini",

    // Provide the conversation messages to the model.
    //
    // `messages` must be an array because a conversation can
    // contain multiple messages from the user, assistant, or system.
    messages: [{

        // Define who sent this message.
        //
        // The role `user` means this message comes from the person
        // interacting with the AI.
        role: 'user',

        // The actual text being sent to the model.
        //
        // The model will read this message and generate an appropriate
        // response based on it.
        content: 'Hello Bhaumik here'
    }]

// `create()` returns a Promise because the API request takes time.
//
// `.then()` runs after OpenAI successfully returns the response.
//
// The `response` parameter contains the complete response object
// returned by the OpenAI API.
}).then(response => {

    // Print the generated assistant message to the terminal.
    //
    // `response.choices` is an array of possible model responses.
    //
    // `response.choices[0]` selects the first generated response.
    //
    // `.message` contains information about the assistant message,
    // including its role and content.
    //
    // `.content` contains the actual text generated by the model.
    console.log(response.choices[0].message.content);
});